# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0002_auto_20160831_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentquery',
            name='relizDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата реализации'),
        ),
    ]
