# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('lombards', '0003_percentquery_relizdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentquery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Пользователь'),
        ),
    ]
