# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0005_filial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelTable(
            name='filial',
            table='filials',
        ),
    ]
