# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0006_auto_20161026_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='lat',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Latitude(широта)'),
        ),
    ]
