# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 18:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0007_auto_20161026_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='lat',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Latitude(широта)'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='long',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Longitude(долгота)'),
        ),
    ]
