# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 12:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0008_auto_20161026_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(375, 375), (500, 500), (583, 583), (585, 585), (750, 750), (900, 900), (958, 958)], unique=True, verbose_name='Проба')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'Цены проб золота',
                'db_table': 'gold_prices',
                'verbose_name': 'Цена пробы',
            },
        ),
    ]
