# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lombards', '0010_filial_end_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='end_day',
            field=models.CharField(blank=True, choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], help_text='Если оставить пустым то без выходных', max_length=2, verbose_name='Последний рабочий день недели'),
        ),
    ]
